server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: scrapper-service
    data:
      mongodb:
        host: localhost
        port: 27017
        database: scrapper_service

#logging:
#  level:
#    root: DEBUG