server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    service-url:
      defaultZone: localhost:8761/eureka

spring:
  datasource:
    username: scraperService
    password: scraperService
    url: jdbc:postgresql://localhost:5433/scraper_service

webdriver:
  http:
    factory: jdk-http-client
  chrome:
    driver: src/main/resources/driver/chrome/chromedriver_macOS
  #    For Windows (32)
  # webdriver.chrome.driver=src/main/resources/driver/chrome/chromedriver_windows32.exe
  #    For Linux (64)
  # webdriver.chrome.driver=src/main/resources/driver/chrome/chromedriver_linux64
