server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  sql:
    init:
      mode: always
  datasource:
    username: scraperService
    password: scraperService
    url: jdbc:postgresql://localhost:5433/scraper_service

webdriver:
  http:
    factory: jdk-http-client
  chrome:
    driver: src/main/resources/driver/chrome/chromedriver_macOS
  #    For Windows (32)
  # webdriver.chrome.driver=src/main/resources/driver/chrome/chromedriver_windows32.exe
  #    For Linux (64)
  # webdriver.chrome.driver=src/main/resources/driver/chrome/chromedriver_linux64

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql: TRACE

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://${TEMPO_HOST:localhost}:${TEMPO_PORT:9411}/api/v2/spans